#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

## tools
## test connections and outputs
## this just builds a docker file and launches it

cd "${0%/*}"

usage() {
    grep '^##' "$0" | cut -c4- > /dev/stderr
}

while getopts h opt; do
    case "${opt}" in
        h) usage; exit 0 ;;
        \?) usage; exit 1 ;;
    esac
done

docker build -t tools . && docker run -it --rm tools
